# Generated by Django 4.0 on 2022-04-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myNotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stickynotes',
            old_name='date',
            new_name='dateOf',
        ),
        migrations.RenameField(
            model_name='stickynotes',
            old_name='text',
            new_name='textIs',
        ),
        migrations.RenameField(
            model_name='stickynotes',
            old_name='useid',
            new_name='userid',
        ),
    ]
