# Generated by Django 4.0 on 2022-04-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myNotes', '0003_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='clink',
        ),
    ]
